### PR TITLE
update dockerfile

### PR DESCRIPTION
**Pull request by relvao**

### CODE REVIEW

**Review by Thurfjell — APPROVED** [review]

**Review by alfonsograziano — APPROVED** [review]
My Docker knowledge is a little bit rusty, but LGTM

**Comment by williamwd** [comment]
I'll add a step on the pipeline to build the dependencies before all services

**Review by peschina — APPROVED** [review]
LGTM, can you please make sure there is a newline at the end of each file?

**Comment by williamwd** [comment]
> LGTM, can you please make sure there is a newline at the end of each file?

So sorry, didn't see your comment until I finished the PR. I have an upcoming PR to improve the pipeline, will take care of it there.

**Pull request merged**
