### PR TITLE
feat: update profile api with entitlements and user details endpoints

### PR DESCRIPTION
**Pull request by GiuliaTeggi**
### Ticket:

- [15378](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/15378)

### Description

- Add `/user` and `/entitlements` endpoints
- Update profile app to use such api endpoints via the building blocks sdk

## Type

- [ ] **Dependency upgrade**
- [ ] **Bug fix**
- [x] **New feature**
- [ ] **Dev change**

### Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works

### Screenshots:

N/A

### CODE REVIEW

**Comment by edge33** [comment]
LGTM

**Review by Thurfjell — COMMENTED** [review]
Quick question.

The rest api doesn't have the `data:T ` response does it? If I curl the endpoints here, I'd get the the T straight up?

Correct me if I'm wrong.

**Comment by GiuliaTeggi** [comment]
> Quick question.
> 
> The rest api doesn't have the `data:T ` response does it? If I curl the endpoints here, I'd get the the T straight up?
> 
> Correct me if I'm wrong.

Yes, the data prop is added by the `sdk` right now

**Comment by GiuliaTeggi** [comment]
> Quick question.
> 
> The rest api doesn't have the `data:T ` response does it? If I curl the endpoints here, I'd get the the T straight up?
> 
> Correct me if I'm wrong.

Yes exactly, I followed the pattern I found on payments, but happy to change this if that's what we all agree to do?

**Pull request merged**
