### PR TITLE
[Payments spike] optional authentication

### PR DESCRIPTION
**Pull request by peschina**
### Ticket:

- [21832](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/21832)

### Description

Optional authentication currently implemented for manual bank transfer only.

## Type

- [ ] **Dependency upgrade**
- [ ] **Bug fix**
- [x] **New feature**
- [ ] **Dev change**
- [ ] **Additional tests**
- [ ] **Documentation**
- [ ] **Other**

### Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] This change might impact the developer experience of others and should be communicated

### Screenshots:

N/A

### CODE REVIEW

**Comment by SamSalvatico** [comment]
Do we still need this?

**Comment by peschina** [comment]
I think we don't, @alfonsograziano  can confirm

**Comment by alfonsograziano** [comment]
Yesss, I agree. This has been a spike, but we can remove it for now if we don't need it

**Comment by SamSalvatico** [comment]
Closing pr as discussed with @peschina and @alfonsograziano

**Pull request closed without merging**
